let ayer = new Date(2018, 2, 20, 02)
let hoy = new Date()
let unDia= new Date (122344355)

console.log(ayer)
console.log(hoy)
console.log(hoy.getDay())
console.log(hoy.getFullYear())
console.log(unDia)
console.log(hoy.getTime())